# Generated by Django 3.2.9 on 2021-11-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(max_length=10)),
                ('dVerificador', models.CharField(max_length=1)),
                ('primerNombre', models.CharField(max_length=20)),
                ('segundoNombre', models.CharField(max_length=20)),
                ('primerApellido', models.CharField(max_length=20)),
                ('segundoApellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=3)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.IntegerField(max_length=9)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(max_length=10)),
                ('dVerificador', models.CharField(max_length=1)),
                ('primerNombre', models.CharField(max_length=20)),
                ('segundoNombre', models.CharField(max_length=20)),
                ('primerApellido', models.CharField(max_length=20)),
                ('segundoApellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=3)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.IntegerField(max_length=9)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.CharField(max_length=70)),
                ('tipoContrato', models.CharField(max_length=20)),
                ('sueldo', models.IntegerField(max_length=8)),
                ('sucursal', models.CharField(max_length=60)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGalenos.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('valor', models.IntegerField(max_length=6)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppGalenos.paciente')),
            ],
        ),
    ]
