# Generated by Django 3.2.9 on 2021-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGalenos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='valor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sueldo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
