# Generated by Django 3.2.9 on 2021-11-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGalenos', '0002_auto_20211125_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='AppGalenos.medico'),
            preserve_default=False,
        ),
    ]
