# Generated by Django 3.2.9 on 2021-11-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGalenos', '0004_alter_hora_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppGalenos.paciente'),
        ),
    ]
