# Generated by Django 3.2.9 on 2021-11-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGalenos', '0005_alter_hora_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='hora',
            field=models.TimeField(),
        ),
    ]
